from engine.models import (
    PartSpec,
    RemainingPiece,
    SheetSpec,
    SheetLayout,
    LayoutResult,
)

class LayoutEngine:
    name = "base"

    def layout(self, parts: list[PartSpec], sheets: list[SheetSpec], settings: dict) -> LayoutResult:
        raise NotImplementedError

    def record_remaining_parts(self, sheet_layouts: list[SheetLayout], roots):
        """
        save remaining parts from nodes generated by layout algorithms.
        """
        
        for sheet_layout, root in zip(sheet_layouts, roots):
            free_nodes = sorted(root.free_nodes(), key=lambda node: (node.y, node.x))
            sheet_layout.remaining_parts = [
                RemainingPiece(node.x, node.y, node.width, node.height)
                for node in free_nodes
                if node.width > 0 and node.height > 0
            ]